### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by oksas** [NoDivide/astrum#2]
I was a little reluctant to post this because I don't really feel like I can give a lot of info on this, but I just downloaded Astrum on two of my Windows machines (both running 64-bit Windows 7) and while it seemed to install just fine with `npm install astrum -g`, running `astrum init ./public/pattern-library` causes the terminal to just hang, for as long as I'll let it, with no sort of errors or anything given. I've tried a few variations of the init command:
- in an empty directory
- in an existing project directory
- with the public/pattern-library folders already made (and empty)
- _without_ the public/pattern-library folders pre-made
- with the path specified absolutely (eg `astrum init c:\web\astrum-sample`)

Actually, all of the `astrum` commands seem to produce the same result :( Running `astrum` or just `astrum init` produces the same hung-terminal effect.

If there are any other details I can provide I would be happy to! I'm not sure if there's some way I can tell Node on my machine to give me some actual error messages? In any event, if there's anything else I can do, I'd be happy to help. If there's something I'm missing and this is a user-error, please let me know D: Astrum looks like an excellent tool and I'm really excited to try it out!

**Comment by osalvador** [comment]
Hi,

I have exactly the same problem. I'm using windows 10 64bits node v4.4.7.

**Comment by RyanHavoc** [comment]
@oksas @osalvador I've just published a new release that should resolve your issues. Run:

    npm update -g astrum

**Comment by oksas** [comment]
It works now :dancer: Thanks so much @RyanHavoc for such a quick fix (and for all your work on Astrum in the first place). Very much looking forward to using Astrum :D

**Comment by RyanHavoc** [comment]
@oksas No worries. Thanks for bring the issue to our attention. Hope you enjoy Astrum. :-)

**Comment by krnlde** [comment]
Hey Guys,
I still get the "hang" reproducibly, not randomly when doing this:
![image](https://user-images.githubusercontent.com/1087002/27079389-bb265f44-5037-11e7-96ed-328adcc3763e.png)

Win10 Pro 64 Node 8.1.0, npm 5.0.3, Astrum 1.9.4

**Comment by lDestiny** [comment]
During component options setup, the scenario is stoped. What I do wrong?
![image](https://user-images.githubusercontent.com/10610518/52838782-9ecfbf00-3115-11e9-9cd8-e70fd686c588.png)
Win10 Pro 64 Node 8.1.0, npm 10.13.0, Astrum 1.9.5

**Comment by NonPolynomial** [comment]
@lDestiny The only thing that the CLI does, is to extend the astrum config with objects and to write template files (`.md` & `.html`).
So you could create those files yourself and write your new component in the astrum config file.

**Comment by lDestiny** [comment]
@NonPolynomial thanks, already do it. I'm very sorry, that the development of this project was to end.

**Comment by Davy803** [comment]
@NonPolynomial Same issue as @IDestiny  with Win 10 x64, Node 12.12.0, npm 6.11.3, Astrum 19.5.
